Interface: fix drop_packet_type missing attribute (#8)
Fix the following error:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pimdm/InterfacePIM.py", line 152, in send_hello
    self.send(packet.bytes())
  File "/usr/local/lib/python3.7/dist-packages/pimdm/InterfacePIM6.py", line 86, in send
    super().send(data=data, group_ip=group_ip)
  File "/usr/local/lib/python3.7/dist-packages/pimdm/InterfacePIM.py", line 113, in send
    if self.drop_packet_type is not None:
AttributeError: 'InterfacePim6' object has no attribute 'drop_packet_type'
```